---
# defaults file for partitions

partitions:
  - number: 1
    name: "boot"
    device: "/dev/sda"
    label: "gpt"
    flags:
      - boot
    part_start: "0%"
    part_end: "512MB"
    part_type: "primary"

  - number: 2
    name: "system"
    device: "/dev/sda"
    label: "gpt"
    flags:
      - lvm
    part_start: "513MB"
    part_end: "100%"
    part_type: "primary"

partitions_vg:
  - vg: "vg_arch"
    pvs: "/dev/sda2"

partitions_lv:
  - lv: "lv_swap"
    vg: "vg_arch"
    size: "1G"

  - lv: "lv_root"
    vg: "vg_arch"
    size: "+100%FREE"
    force: true

partitions_ext4:
  - /dev/sda1
  - /dev/mapper/vg_arch-lv_root

partitions_swap:
  - /dev/mapper/vg_arch-lv_swap
