---
# defaults file for partitions

parted_partitions:
  - number: "1"
    device: "/dev/sda"
    label: "gpt"
    flags: "boot"
    part_start: "0%"
    part_end: "512MiB"
    part_type: "primary"
    state: "present"
  - number: "2"
    device: "/dev/sda"
    label: "gpt"
    flags: "lvm"
    part_start: "513MiB"
    part_end: "100%"
    part_type: "primary"
    state: "present"
