---
# tasks file for partitions

- name: Partition disck
  parted:
    number: "{{ item.number }}"
    device: "{{ item.device }}"
    label: "{{ item.label | default('gpt') }}"
    part_start: "{{ item.part_start }}"
    part_end: "{{ item.part_end }}"
    part_type: "{{ item.part_type | default('primary') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ parted_partitions }}"
