---
# tasks file for partitions

- name: Partition disck
  parted:
    number: "{{ item.number }}"
    name: "{{ item.name | default(omit) }}"
    device: "{{ item.device }}"
    label: "{{ item.label | default('gpt') }}"
    flags: "{{ item.flags | default(omit) }}"
    part_start: "{{ item.part_start | default(omit) }}"
    part_end: "{{ item.part_end | default(omit) }}"
    part_type: "{{ item.part_type | default('primary') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ parted_partitions }}"
